name: Code Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyright
          pip install -r requirements.txt

      - name: Run ruff format check
        run: ruff format --check .

      - name: Run ruff linting
        run: ruff check .

      - name: Run pyright type checking
        run: pyright
