name: Update MaccabiPedia Calendar
on:
  schedule:
    - cron: "5 21 * * *"
  workflow_dispatch:

jobs:
  update-maccabipedia-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.13
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update MaccabiPedia Calendar
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          FOOTBALL_CALENDAR_ID: ${{ secrets.FOOTBALL_CALENDAR_ID }}
          BASKETBALL_CALENDAR_ID: ${{ secrets.BASKETBALL_CALENDAR_ID }}
          VOLLEYBALL_CALENDAR_ID: ${{ secrets.VOLLEYBALL_CALENDAR_ID }}
          HANDBALL_CALENDAR_ID: ${{ secrets.HANDBALL_CALENDAR_ID }}
          CALENDAR_TO_UPDATE: ${{ secrets.CALENDAR_TO_UPDATE }}
        run: python main.py
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
