name: Update MaccabiPedia Calendar
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  update-maccabipedia-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "./google-credentials.json"
          json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Update MaccabiPedia Calendar
        env:
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python main.py
